const ADD_MOVIE = "ADD_MOVIE";
const DELETE_MOVIE = "DELETE_MOVIE";
const UPDATE_MOVIE = "UPDATE_MOVIE";
const GET_ALL_MOVIES = "GET_ALL_MOVIES";
const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
const EMPTY_MOVIE_LIST = 'EMPTY_MOVIE_LIST';

const ADD_ACTOR = "ADD_ACTOR";
const DELETE_ACTOR = "DELETE_ACTOR";
const UPDATE_ACTOR = "UPDATE_ACTOR";
const GET_ALL_ACTORS = "GET_ALL_ACTORS";
const GET_ACTOR_DETAILS = "GET_ACTOR_DETAILS";
const EMPTY_ACTOR_LIST = "EMPTY_ACTOR_LIST";

const ASSIGN_ACTOR_TO_MOVIE = "ASSIGN_ACTOR_TO_MOVIE";
const UNLINK_ACTOR_FROM_MOVIE = "UNLINK_ACTOR_FROM_MOVIE";

export const actionContants = {
    ADD_MOVIE,
    DELETE_MOVIE,
    UPDATE_MOVIE,
    GET_ALL_MOVIES,
    GET_MOVIE_DETAILS,
    ADD_ACTOR,
    DELETE_ACTOR,
    UPDATE_ACTOR,
    GET_ALL_ACTORS,
    GET_ACTOR_DETAILS,
    ASSIGN_ACTOR_TO_MOVIE,
    UNLINK_ACTOR_FROM_MOVIE,
    EMPTY_MOVIE_LIST,
    EMPTY_ACTOR_LIST
}