"""empty message

Revision ID: f5b09cb4b275
Revises: df62a934e309
Create Date: 2020-04-09 07:30:18.264330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b09cb4b275'
down_revision = 'df62a934e309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TABLE actors DROP CONSTRAINT actors_pkey")
    op.execute("ALTER TABLE actors ADD CONSTRAINT actors_pkey PRIMARY KEY(id)")

    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
